version: '3.6'

services:
  springboot-app:
    image: your-springboot-app-image
    container_name: springboot-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      VAULT_ADDR: 'http://vault:8200'
      SPRING_PROFILES_ACTIVE: 'docker'
    networks:
      - sk_cloud

networks:
  sk_cloud:
    external: true
